using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.9.0.0")]
[assembly: AssemblyTitleAttribute("Chronos")]
[assembly: AssemblyDescriptionAttribute("Orion\'s Belt Engine")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2004, Sapos Dominadores")]
[assembly: AssemblyInformationalVersionAttribute("Debug: false; Persistence: npgsql; OS: win32; TargetPlatform: net-1.1; Wiki: true" +
";")]

